export const paxData_PMDG77W = [
    {
        paxLevel: "100%",
        first: "12",
        business: "42",
        economy: "316",
        ttlPax: "370",
        firstPercentage: "3.24%",
        businessPercentage: "11.35%",
        economyPercentage: "85.41%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "99%",
        first: "12",
        business: "42",
        economy: "313",
        ttlPax: "367",
        firstPercentage: "3.27%",
        businessPercentage: "11.44%",
        economyPercentage: "85.29%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "98%",
        first: "12",
        business: "41",
        economy: "310",
        ttlPax: "363",
        firstPercentage: "3.31%",
        businessPercentage: "11.29%",
        economyPercentage: "85.40%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "97%",
        first: "12",
        business: "41",
        economy: "307",
        ttlPax: "360",
        firstPercentage: "3.33%",
        businessPercentage: "11.39%",
        economyPercentage: "85.28%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "96%",
        first: "12",
        business: "40",
        economy: "303",
        ttlPax: "355",
        firstPercentage: "3.38%",
        businessPercentage: "11.27%",
        economyPercentage: "85.35%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "95%",
        first: "11",
        business: "40",
        economy: "300",
        ttlPax: "351",
        firstPercentage: "3.13%",
        businessPercentage: "11.40%",
        economyPercentage: "85.47%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "94%",
        first: "11",
        business: "39",
        economy: "297",
        ttlPax: "347",
        firstPercentage: "3.17%",
        businessPercentage: "11.24%",
        economyPercentage: "85.59%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "93%",
        first: "11",
        business: "39",
        economy: "294",
        ttlPax: "344",
        firstPercentage: "3.20%",
        businessPercentage: "11.34%",
        economyPercentage: "85.47%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "92%",
        first: "11",
        business: "39",
        economy: "291",
        ttlPax: "341",
        firstPercentage: "3.23%",
        businessPercentage: "11.44%",
        economyPercentage: "85.34%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "91%",
        first: "11",
        business: "38",
        economy: "288",
        ttlPax: "337",
        firstPercentage: "3.26%",
        businessPercentage: "11.28%",
        economyPercentage: "85.46%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "90%",
        first: "11",
        business: "38",
        economy: "284",
        ttlPax: "333",
        firstPercentage: "3.30%",
        businessPercentage: "11.41%",
        economyPercentage: "85.29%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "89%",
        first: "11",
        business: "37",
        economy: "281",
        ttlPax: "329",
        firstPercentage: "3.34%",
        businessPercentage: "11.25%",
        economyPercentage: "85.41%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "88%",
        first: "11",
        business: "37",
        economy: "278",
        ttlPax: "326",
        firstPercentage: "3.37%",
        businessPercentage: "11.35%",
        economyPercentage: "85.28%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "87%",
        first: "10",
        business: "37",
        economy: "275",
        ttlPax: "322",
        firstPercentage: "3.11%",
        businessPercentage: "11.49%",
        economyPercentage: "85.40%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "86%",
        first: "10",
        business: "36",
        economy: "272",
        ttlPax: "318",
        firstPercentage: "3.14%",
        businessPercentage: "11.32%",
        economyPercentage: "85.53%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "85%",
        first: "10",
        business: "36",
        economy: "269",
        ttlPax: "315",
        firstPercentage: "3.17%",
        businessPercentage: "11.43%",
        economyPercentage: "85.40%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "84%",
        first: "10",
        business: "35",
        economy: "265",
        ttlPax: "310",
        firstPercentage: "3.23%",
        businessPercentage: "11.29%",
        economyPercentage: "85.48%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "83%",
        first: "10",
        business: "35",
        economy: "262",
        ttlPax: "307",
        firstPercentage: "3.26%",
        businessPercentage: "11.40%",
        economyPercentage: "85.34%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "82%",
        first: "10",
        business: "34",
        economy: "259",
        ttlPax: "303",
        firstPercentage: "3.30%",
        businessPercentage: "11.22%",
        economyPercentage: "85.48%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "81%",
        first: "10",
        business: "34",
        economy: "256",
        ttlPax: "300",
        firstPercentage: "3.33%",
        businessPercentage: "11.33%",
        economyPercentage: "85.33%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "80%",
        first: "10",
        business: "34",
        economy: "253",
        ttlPax: "297",
        firstPercentage: "3.37%",
        businessPercentage: "11.45%",
        economyPercentage: "85.19%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "79%",
        first: "9",
        business: "33",
        economy: "250",
        ttlPax: "292",
        firstPercentage: "3.08%",
        businessPercentage: "11.30%",
        economyPercentage: "85.62%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "78%",
        first: "9",
        business: "33",
        economy: "246",
        ttlPax: "288",
        firstPercentage: "3.13%",
        businessPercentage: "11.46%",
        economyPercentage: "85.42%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "77%",
        first: "9",
        business: "32",
        economy: "243",
        ttlPax: "284",
        firstPercentage: "3.17%",
        businessPercentage: "11.27%",
        economyPercentage: "85.56%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "76%",
        first: "9",
        business: "32",
        economy: "240",
        ttlPax: "281",
        firstPercentage: "3.20%",
        businessPercentage: "11.39%",
        economyPercentage: "85.41%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "75%",
        first: "9",
        business: "32",
        economy: "237",
        ttlPax: "278",
        firstPercentage: "3.24%",
        businessPercentage: "11.51%",
        economyPercentage: "85.25%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "74%",
        first: "9",
        business: "31",
        economy: "234",
        ttlPax: "274",
        firstPercentage: "3.28%",
        businessPercentage: "11.31%",
        economyPercentage: "85.40%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "73%",
        first: "9",
        business: "31",
        economy: "231",
        ttlPax: "271",
        firstPercentage: "3.32%",
        businessPercentage: "11.44%",
        economyPercentage: "85.24%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "72%",
        first: "9",
        business: "30",
        economy: "228",
        ttlPax: "267",
        firstPercentage: "3.37%",
        businessPercentage: "11.24%",
        economyPercentage: "85.39%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "71%",
        first: "9",
        business: "30",
        economy: "224",
        ttlPax: "263",
        firstPercentage: "3.42%",
        businessPercentage: "11.41%",
        economyPercentage: "85.17%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "70%",
        first: "8",
        business: "29",
        economy: "221",
        ttlPax: "258",
        firstPercentage: "3.10%",
        businessPercentage: "11.24%",
        economyPercentage: "85.66%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "69%",
        first: "8",
        business: "29",
        economy: "218",
        ttlPax: "255",
        firstPercentage: "3.14%",
        businessPercentage: "11.37%",
        economyPercentage: "85.49%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "68%",
        first: "8",
        business: "29",
        economy: "215",
        ttlPax: "252",
        firstPercentage: "3.17%",
        businessPercentage: "11.51%",
        economyPercentage: "85.32%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "67%",
        first: "8",
        business: "28",
        economy: "212",
        ttlPax: "248",
        firstPercentage: "3.23%",
        businessPercentage: "11.29%",
        economyPercentage: "85.48%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "66%",
        first: "8",
        business: "28",
        economy: "209",
        ttlPax: "245",
        firstPercentage: "3.27%",
        businessPercentage: "11.43%",
        economyPercentage: "85.31%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "65%",
        first: "8",
        business: "27",
        economy: "205",
        ttlPax: "240",
        firstPercentage: "3.33%",
        businessPercentage: "11.25%",
        economyPercentage: "85.42%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "64%",
        first: "8",
        business: "27",
        economy: "202",
        ttlPax: "237",
        firstPercentage: "3.38%",
        businessPercentage: "11.39%",
        economyPercentage: "85.23%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "63%",
        first: "8",
        business: "26",
        economy: "199",
        ttlPax: "233",
        firstPercentage: "3.43%",
        businessPercentage: "11.16%",
        economyPercentage: "85.41%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "62%",
        first: "7",
        business: "26",
        economy: "196",
        ttlPax: "229",
        firstPercentage: "3.06%",
        businessPercentage: "11.35%",
        economyPercentage: "85.59%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "61%",
        first: "7",
        business: "26",
        economy: "193",
        ttlPax: "226",
        firstPercentage: "3.10%",
        businessPercentage: "11.50%",
        economyPercentage: "85.40%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "60%",
        first: "7",
        business: "25",
        economy: "190",
        ttlPax: "222",
        firstPercentage: "3.15%",
        businessPercentage: "11.26%",
        economyPercentage: "85.59%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "59%",
        first: "7",
        business: "25",
        economy: "186",
        ttlPax: "218",
        firstPercentage: "3.21%",
        businessPercentage: "11.47%",
        economyPercentage: "85.32%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "58%",
        first: "7",
        business: "24",
        economy: "183",
        ttlPax: "214",
        firstPercentage: "3.27%",
        businessPercentage: "11.21%",
        economyPercentage: "85.51%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "57%",
        first: "7",
        business: "24",
        economy: "180",
        ttlPax: "211",
        firstPercentage: "3.32%",
        businessPercentage: "11.37%",
        economyPercentage: "85.31%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "56%",
        first: "7",
        business: "24",
        economy: "177",
        ttlPax: "208",
        firstPercentage: "3.37%",
        businessPercentage: "11.54%",
        economyPercentage: "85.10%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "55%",
        first: "7",
        business: "23",
        economy: "174",
        ttlPax: "204",
        firstPercentage: "3.43%",
        businessPercentage: "11.27%",
        economyPercentage: "85.29%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "54%",
        first: "6",
        business: "23",
        economy: "171",
        ttlPax: "200",
        firstPercentage: "3.00%",
        businessPercentage: "11.50%",
        economyPercentage: "85.50%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "53%",
        first: "6",
        business: "22",
        economy: "167",
        ttlPax: "195",
        firstPercentage: "3.08%",
        businessPercentage: "11.28%",
        economyPercentage: "85.64%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "52%",
        first: "6",
        business: "22",
        economy: "164",
        ttlPax: "192",
        firstPercentage: "3.13%",
        businessPercentage: "11.46%",
        economyPercentage: "85.42%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "51%",
        first: "6",
        business: "21",
        economy: "161",
        ttlPax: "188",
        firstPercentage: "3.19%",
        businessPercentage: "11.17%",
        economyPercentage: "85.64%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "50%",
        first: "6",
        business: "21",
        economy: "158",
        ttlPax: "185",
        firstPercentage: "3.24%",
        businessPercentage: "11.35%",
        economyPercentage: "85.41%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "49%",
        first: "6",
        business: "21",
        economy: "155",
        ttlPax: "182",
        firstPercentage: "3.30%",
        businessPercentage: "11.54%",
        economyPercentage: "85.16%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "48%",
        first: "6",
        business: "20",
        economy: "152",
        ttlPax: "178",
        firstPercentage: "3.37%",
        businessPercentage: "11.24%",
        economyPercentage: "85.39%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "47%",
        first: "6",
        business: "20",
        economy: "149",
        ttlPax: "175",
        firstPercentage: "3.43%",
        businessPercentage: "11.43%",
        economyPercentage: "85.14%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "46%",
        first: "6",
        business: "19",
        economy: "145",
        ttlPax: "170",
        firstPercentage: "3.53%",
        businessPercentage: "11.18%",
        economyPercentage: "85.29%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "45%",
        first: "5",
        business: "19",
        economy: "142",
        ttlPax: "166",
        firstPercentage: "3.01%",
        businessPercentage: "11.45%",
        economyPercentage: "85.54%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "44%",
        first: "5",
        business: "18",
        economy: "139",
        ttlPax: "162",
        firstPercentage: "3.09%",
        businessPercentage: "11.11%",
        economyPercentage: "85.80%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "43%",
        first: "5",
        business: "18",
        economy: "136",
        ttlPax: "159",
        firstPercentage: "3.14%",
        businessPercentage: "11.32%",
        economyPercentage: "85.53%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "42%",
        first: "5",
        business: "18",
        economy: "133",
        ttlPax: "156",
        firstPercentage: "3.21%",
        businessPercentage: "11.54%",
        economyPercentage: "85.26%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "41%",
        first: "5",
        business: "17",
        economy: "130",
        ttlPax: "152",
        firstPercentage: "3.29%",
        businessPercentage: "11.18%",
        economyPercentage: "85.53%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "40%",
        first: "5",
        business: "17",
        economy: "126",
        ttlPax: "148",
        firstPercentage: "3.38%",
        businessPercentage: "11.49%",
        economyPercentage: "85.14%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "39%",
        first: "5",
        business: "16",
        economy: "123",
        ttlPax: "144",
        firstPercentage: "3.47%",
        businessPercentage: "11.11%",
        economyPercentage: "85.42%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "38%",
        first: "5",
        business: "16",
        economy: "120",
        ttlPax: "141",
        firstPercentage: "3.55%",
        businessPercentage: "11.35%",
        economyPercentage: "85.11%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "37%",
        first: "4",
        business: "16",
        economy: '117',
        ttlPax: "137",
        firstPercentage: "2.92%",
        businessPercentage: "11.68%",
        economyPercentage: "85.40%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "36%",
        first: "4",
        business: "15",
        economy: "114",
        ttlPax: "133",
        firstPercentage: "3.01%",
        businessPercentage: "11.28%",
        economyPercentage: "85.71%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "35%",
        first: "4",
        business: "15",
        economy: "111",
        ttlPax: "130",
        firstPercentage: "3.08%",
        businessPercentage: "11.54%",
        economyPercentage: "85.38%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "34%",
        first: "4",
        business: "14",
        economy: "107",
        ttlPax: "125",
        firstPercentage: "3.20%",
        businessPercentage: "11.20%",
        economyPercentage: "85.60%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "33%",
        first: "4",
        business: "14",
        economy: "104",
        ttlPax: "122",
        firstPercentage: "3.28%",
        businessPercentage: "11.48%",
        economyPercentage: "85.25%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "32%",
        first: "4",
        business: "13",
        economy: "101",
        ttlPax: "118",
        firstPercentage: "3.39%",
        businessPercentage: "11.02%",
        economyPercentage: "85.59%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "31%",
        first: "4",
        business: "13",
        economy: "98",
        ttlPax: "115",
        firstPercentage: "3.48%",
        businessPercentage: "11.30%",
        economyPercentage: "85.22%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "30%",
        first: "4",
        business: "13",
        economy: "95",
        ttlPax: "112",
        firstPercentage: "3.57%",
        businessPercentage: "11.61%",
        economyPercentage: "84.82%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "29%",
        first: "3",
        business: "12",
        economy: "92",
        ttlPax: "107",
        firstPercentage: "2.80%",
        businessPercentage: "11.21%",
        economyPercentage: "85.98%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "28%",
        first: "3",
        business: "12",
        economy: "88",
        ttlPax: "103",
        firstPercentage: "2.91%",
        businessPercentage: "11.65%",
        economyPercentage: "85.44%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "27%",
        first: "3",
        business: "11",
        economy: "85",
        ttlPax: "99",
        firstPercentage: "3.03%",
        businessPercentage: "11.11%",
        economyPercentage: "85.86%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "26%",
        first: "3",
        business: "11",
        economy: "82",
        ttlPax: "96",
        firstPercentage: "3.13%",
        businessPercentage: "11.46%",
        economyPercentage: "85.42%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "25%",
        first: "3",
        business: "11",
        economy: "79",
        ttlPax: "93",
        firstPercentage: "3.23%",
        businessPercentage: "11.83%",
        economyPercentage: "84.95%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "24%",
        first: "3",
        business: "10",
        economy: "76",
        ttlPax: "89",
        firstPercentage: "3.37%",
        businessPercentage: "11.24%",
        economyPercentage: "85.39%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "23%",
        first: "3",
        business: "10",
        economy: "73",
        ttlPax: "86",
        firstPercentage: "3.49%",
        businessPercentage: "11.63%",
        economyPercentage: "84.88%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "22%",
        first: "3",
        business: "9",
        economy: "70",
        ttlPax: "82",
        firstPercentage: "3.66%",
        businessPercentage: "10.98%",
        economyPercentage: "85.37%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "21%",
        first: "3",
        business: "9",
        economy: "66",
        ttlPax: "78",
        firstPercentage: "3.85%",
        businessPercentage: "11.54%",
        economyPercentage: "84.62%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "20%",
        first: "2",
        business: "8",
        economy: "63",
        ttlPax: "73",
        firstPercentage: "2.74%",
        businessPercentage: "10.96%",
        economyPercentage: "86.30%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "19%",
        first: "2",
        business: "8",
        economy: "60",
        ttlPax: "70",
        firstPercentage: "2.86%",
        businessPercentage: "11.43%",
        economyPercentage: "85.71%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "18%",
        first: "2",
        business: "8",
        economy: "57",
        ttlPax: "67",
        firstPercentage: "2.99%",
        businessPercentage: "11.94%",
        economyPercentage: "85.07%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "17%",
        first: "2",
        business: "7",
        economy: "54",
        ttlPax: "63",
        firstPercentage: "3.17%",
        businessPercentage: "11.11%",
        economyPercentage: "85.71%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "16%",
        first: "2",
        business: "7",
        economy: "51",
        ttlPax: "60",
        firstPercentage: "3.33%",
        businessPercentage: "11.67%",
        economyPercentage: "85.00%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "15%",
        first: "2",
        business: "6",
        economy: "47",
        ttlPax: "55",
        firstPercentage: "3.64%",
        businessPercentage: "10.91%",
        economyPercentage: "85.45%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "14%",
        first: "2",
        business: "6",
        economy: "44",
        ttlPax: "52",
        firstPercentage: "3.85%",
        businessPercentage: "11.54%",
        economyPercentage: "84.62%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "13%",
        first: "2",
        business: "5",
        economy: "41",
        ttlPax: "48",
        firstPercentage: "4.17%",
        businessPercentage: "10.42%",
        economyPercentage: "85.42%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "12%",
        first: "1",
        business: "5",
        economy: "38",
        ttlPax: "44",
        firstPercentage: "2.27%",
        businessPercentage: "11.36%",
        economyPercentage: "86.36%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "11%",
        first: "1",
        business: "5",
        economy: "35",
        ttlPax: "41",
        firstPercentage: "2.44%",
        businessPercentage: "12.20%",
        economyPercentage: "85.37%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "10%",
        first: "1",
        business: "4",
        economy: "32",
        ttlPax: "37",
        firstPercentage: "2.70%",
        businessPercentage: "10.81%",
        economyPercentage: "86.49%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "9%",
        first: "1",
        business: "4",
        economy: "28",
        ttlPax: "33",
        firstPercentage: "3.03%",
        businessPercentage: "12.12%",
        economyPercentage: "84.85%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "8%",
        first: "1",
        business: "3",
        economy: "25",
        ttlPax: "29",
        firstPercentage: "3.45%",
        businessPercentage: "10.34%",
        economyPercentage: "86.21%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "7%",
        first: "1",
        business: "3",
        economy: "22",
        ttlPax: "26",
        firstPercentage: "3.85%",
        businessPercentage: "11.54%",
        economyPercentage: "84.62%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "6%",
        first: "1",
        business: "3",
        economy: "19",
        ttlPax: "23",
        firstPercentage: "4.35%",
        businessPercentage: "13.04%",
        economyPercentage: "82.61%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "5%",
        first: "1",
        business: "2",
        economy: "16",
        ttlPax: "19",
        firstPercentage: "5.26%",
        businessPercentage: "10.53%",
        economyPercentage: "84.21%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "4%",
        first: "0",
        business: "2",
        economy: "13",
        ttlPax: "15",
        firstPercentage: "0.00%",
        businessPercentage: "13.33%",
        economyPercentage: "86.67%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "3%",
        first: "0",
        business: "1",
        economy: "0",
        ttlPax: "10",
        firstPercentage: "0.00%",
        businessPercentage: "10.00%",
        economyPercentage: "90.00%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "2%",
        first: "0",
        business: "1",
        economy: "6",
        ttlPax: "7",
        firstPercentage: "0.00%",
        businessPercentage: "14.29%",
        economyPercentage: "85.71%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "1%",
        first: "0",
        business: "0",
        economy: "3",
        ttlPax: "3",
        firstPercentage: "0.00%%",
        businessPercentage: "0.00%",
        economyPercentage: "100.00%",
        ttlPercentage: "100.00%"
    },
    {
        paxLevel: "0%",
        first: "0",
        business: "0",
        economy: "0",
        ttlPax: "0",
        firstPercentage: "0.00%",
        businessPercentage: "0.00%",
        economyPercentage: "0.00%",
        ttlPercentage: "0.00%"
    }
]